### PR TITLE
Updating the solution to support Material Icons.

### PR DESCRIPTION
**Pull request by readingdancer**
Hi @skartknet 

I think the Material Icons codepoints files have changed since you last looked at them, they are now plain text file and not JSON data :)

I created this PR will all the changes required to support Material Icons, I have added a couple of extra error messages to help any developers who choose to use Material Icons and I have updated the relevant help page.

I have allowed `.codepoints` files to be selected so that in theory the original files can be used without any requirement to rename them, however as I have explained in the documentation, the web server serving this file has to support the MIME type.

I also added an error message in case someone tries to use this extension and they get a 404 error, as this is likely to be their issue.

I have changed the Regex in the preconfigs.json file and I have added some additional localization words to the US English XML file, sorry I can't help with the Spanish translations, perhaps you can add them?

I also updated all the Material Icons example files in each of your text Umbraco folders so it should be pretty easy to test them locally.

Cheers,

Chris

### CODE REVIEW

**Comment by readingdancer** [comment]
@skartknet 

I hope you had a good weekend, I just wondered if you had a chance to look at my PR and if you needed me to do anything else to get it merged in?

Cheers,

Chris

**Comment by skartknet** [comment]
Hey Chris,

I'll be overseas for a couple of weeks so I won't have time to check your
PR. I'll take a look as soon as I come back.

Thanks.

**Comment by readingdancer** [comment]
Just a little ping in case you are back :)

**Review by skartknet — APPROVED** [review]

**Comment by skartknet** [comment]
Hi @readingdancer , yes I'm back ;). This PR looks great, thanks so much! I will include it in the next version.

**Pull request merged**
