### PR TITLE
Additional documentation folders & readmes

### PR DESCRIPTION
**Pull request by hfloyd**
Plus Font Awesome 5 config info and files.

### CODE REVIEW

**Comment by skartknet** [comment]
This PR is great!

**Comment by hfloyd** [comment]
Thanks! I'm glad you like.

**Comment by hfloyd** [comment]
Oh, I didn't make any updates to the main readme... Maybe you could just add a link so people know the documentation is available?

**Comment by skartknet** [comment]
I already did that :)

**Comment by hfloyd** [comment]
Oh, looks great!

**Pull request merged**
